### ISSUE TITLE
Option to disable "Time until dawn" message

### ISSUE THREAD

**Issue by Muhammed-Al-Abdul-Gader** [Steveplays28/realisticsleep#16]
Option for disabling the "time until dawn" feature? Or compatibility with mods allowing to sleep during the day (Just the message in bed) Or "time until dusk"

**Comment by Steveplays28** [comment]
Thanks for opening an issue!

I'll see when I can work on the next release, and probably include this feature.

**Comment by Steveplays28** [comment]
I just checked the code, you're able to just make the `dawnMessage` field in the config empty (`""`) and it won't send a message to the action bar.

https://github.com/Steveplays28/realisticsleep/blob/ca842863843e35f18857d05c1b91f6343f6619d5/src/main/java/com/github/steveplays28/realisticsleep/mixin/ServerWorldMixin.java#L137-L145
