### ISSUE TITLE
REQUEST: Config option for displaying timer

### ISSUE THREAD

**Issue by SwordShaman** [Steveplays28/realisticsleep#17]
It's a rather trivial thing, but I try to keep my UI as uncluttered as possible.  Would you be willing to give a config option to disable the status while sleeping? (e.g. 1/1 players are sleeping through this night. (time until dawn: x s)

Thanks for the mod, btw.  Exactly what I was looking for.  :)

**Comment by Steveplays28** [comment]
Of course, I'll put this on the list.
Have been busy with school and other things lately, I'll see when I get back to this mod and finish the update.

**Comment by Steveplays28** [comment]
I've implemented this feature, will release a new version (1.7.0) in the next few days, which will also fix a compat issue and have some cleaner code.

You've got 2 new options for enabling/disabling the not enough players sleeping message, and the x players are sleeping (time until dawn: y) message.

**Comment by Steveplays28** [comment]
[1.7.0](https://github.com/Steveplays28/realisticsleep/releases/tag/1.7.0) has been released, which includes a config option for disabling the actionbar text!

[Modrinth](https://modrinth.com/mod/realisticsleep/versions/1.7.0)
[CurseForge](https://www.curseforge.com/minecraft/mc-mods/realisticsleepfabric)
