### ISSUE TITLE
Players get kicked out of bed slightly earlier than they should

### ISSUE THREAD

**Issue by Steveplays28** [Steveplays28/realisticsleep#20]
Submitted by [Nomporu](https://www.curseforge.com/members/nomporu/projects) on CurseForge

**Comment by Steveplays28** [comment]
Can't reproduce on 1.19.2 Quilt and 1.19.3 Quilt using the latest version of Realistic Sleep (1.7.0).

**Comment by Raph404** [comment]
I think I know the problem. Using a GUI clock mod, the "morning" shows at 6am. Normally, RealisticSleep run until 05:15am, but when you se the multipliers to say, 50, you wake up even earlier around 04:15. 

Basically Minecraft is set to let you still sleep until 6am, but the mod thinks it is already morning when it isn't and kicks you out right away

**Comment by Steveplays28** [comment]
Yeah that's a small bug I haven't had time to solve yet. I need to kick the players out of bed a few seconds earlier because otherwise it wouldn't work at all.
I'll see what I can do at some point, just got some other things to do at the moment. Feel free to PR a fix in the meantime if you want to.

**Comment by Steveplays28** [comment]
This has been fixed in `v1.8.0`.
