### ISSUE TITLE
Crashes upon opening config window

### ISSUE THREAD

**Issue by Tac0-guy** [Steveplays28/realisticsleep#24]
essentially the same as the title. when I use this alongside the mod menu it works fine until I try to configure the settings inside the mod menu. Mod is very cool and works fine until I try to customize it the second I click the settings tab it saves and exits the world.
use in Java 1.19.3
This is the error code it gives out
java.lang.NoSuchFieldError: field_25035

**Comment by Steveplays28** [comment]
Hi, thanks for the report.
Do you mind pasting the full crash log? I'm currently missing some valuable information like the classes and full stack trace.

This could also be a Cloth Config issue, try upgrading/downgrading Cloth Config.

**Comment by Tac0-guy** [comment]
> Hi, thanks for the report.
> Do you mind pasting the full crash log? I'm currently missing some valuable information like the classes and full stack trace.
> 
> This could also be a Cloth Config issue, try upgrading/downgrading Cloth Config.
> 

I will attempt to change my cloth config do you have a recommendation on the version I should use? Currently using version 9.0.94 

Moreover can you direct me to what information or where the information you need would be? I copied the error code directly from the crash window.

**Comment by Tac0-guy** [comment]
Problem resolved i simply re-downloaded cloth config and it fixed itself. I used the same version and changed nothing.  Thank you for your recommendation!

**Comment by Steveplays28** [comment]
Alright, no worries! Glad the issue is solved.
