### ISSUE TITLE
Can you set a percentage of people to sleep?

### ISSUE THREAD

**Issue by QianMuu** [Steveplays28/realisticsleep#25]
I don't know if there is this setting, but it needs everyone to sleep at night to skip it, which is difficult to do, so can we skip the setting at night if we can increase the number of people sleeping by a percentage

**Comment by QianMuu** [comment]
I think what I mean is that if you set a percentage of the number of people, there are ten people in the server, and only three people need to sleep, you can skip the night.

I'm not sure if I didn't see it clearly, but I didn't find this setting.

**Comment by Steveplays28** [comment]
Yes, you can change that. In the in game chat, do `/gamerule playersSleepPercentage x` where `x` is the percentage of people in the server that are needed to sleep at once to skip the night.
