### ISSUE TITLE
Sleeping resets day counter

### ISSUE THREAD

**Issue by DailyEffortBird** [Steveplays28/realisticsleep#26]
This is an issue on it's own but it also causes issues with Fabric Seasons because it never progresses past spring.
using 1.18.2

**Comment by Steveplays28** [comment]
What version of Realistic sleep are you using?
This issue should be fixed in 1.7.0.

**Comment by DailyEffortBird** [comment]
Realistic sleep 1.4
Minecraft 1.18.2

**Comment by Steveplays28** [comment]
You should update Realistic Sleep to [1.7.0](https://github.com/Steveplays28/realisticsleep/releases/tag/1.7.0), this will fix the issue you're having.
