### ISSUE TITLE
Make entities like furnaces around players tick faster while sleeping

### ISSUE THREAD

**Issue by Steveplays28** [Steveplays28/realisticsleep#3]

**Comment by TalEdd** [comment]
You might be able to use [https://modrinth.com/mod/sleep-warp](url)/[https://github.com/Giggitybyte/SleepWarp](url)'s implementation of block entity ticking.

**Comment by Steveplays28** [comment]
That's a good point, thank you!

I'm going to make the config reload when mod menu updates it, and then upload a new build. Sorry for the fluke build earlier.

**Comment by Steveplays28** [comment]
I rewrote the config code and improved the default config.
The furnace ticking seems to speed up properly now :D

I'm closing this issue.
