### ISSUE TITLE
Latest Fabric 1.19.3 update fails MC to load into world

### ISSUE THREAD

**Issue by Cape-City** [Steveplays28/realisticsleep#32]
With the latest update realisticsleep-1.7.1+mc1.18.x-1.19.x.jar MC is stuck in a loop during loading into the world.
Going back to version realisticsleep-1.7.0.jar and the issue isn't present anymore.

[latest.log](https://github.com/Steveplays28/realisticsleep/files/11778701/latest.log)

**Comment by Steveplays28** [comment]
Could you send me your Realistic Sleep config?

**Comment by Cape-City** [comment]
This is how the config is set to:
{
  "dawnMessage": "The sun rises.",
  "sendSleepingMessage": true,
  "sendNotEnoughPlayersSleepingMessage": true,
  "sleepSpeedCurve": "LINEAR",
  "sleepSpeedMultiplier": 25.0,
  "blockEntityTickSpeedMultiplier": 25.0,
  "chunkTickSpeedMultiplier": 25.0,
  "raidTickSpeedMultiplier": 25.0,
  "tickDelay": -1
}

**Comment by Cape-City** [comment]
I delete the config and let the new version create the defaults:

{
  "dawnMessage": "The sun rises.",
  "sendSleepingMessage": true,
  "sendNotEnoughPlayersSleepingMessage": true,
  "sleepSpeedCurve": "LINEAR",
  "sleepSpeedMultiplier": 25.0,
  "blockEntityTickSpeedMultiplier": 25.0,
  "chunkTickSpeedMultiplier": 1.0,
  "raidTickSpeedMultiplier": 25.0,
  "tickDelay": -1
}

The issue is still the same, a loop while loading the world.

**Comment by Steveplays28** [comment]
Hmm, odd. I'll have to do some testing. Might be a while since exams are starting though.

**Comment by darknesschaos** [comment]
I am getting this issue for 1.19.2 as well.

**Comment by Steveplays28** [comment]
@Cape-City Could you try setting all the speedup multipliers to `1.0`?
I wonder if it's an issue of everything ticking too fast.

**Comment by Cape-City** [comment]
Even with this config:

{
  "dawnMessage": "The sun rises.",
  "sendSleepingMessage": true,
  "sendNotEnoughPlayersSleepingMessage": true,
  "sleepSpeedCurve": "LINEAR",
  "sleepSpeedMultiplier": 1.0,
  "blockEntityTickSpeedMultiplier": 1.0,
  "chunkTickSpeedMultiplier": 1.0,
  "raidTickSpeedMultiplier": 1.0,
  "tickDelay": -1
}

The games seems to be stuck in an endless loop while loading into the world.

**Comment by Steveplays28** [comment]
Alright, that's super odd.
I'll be on vacation, so I'll only be back in a week or two. I'll look into it in more detail and write some tests then.

**Comment by Cape-City** [comment]
The same issue happens with 1.19.4 aswell, but not, if the realistic sleep mod is the only one installed - so it seems to be an incomp with an existing mod during loading process.

As I told before, the old version is working fine so far. So don't be in a hurry and have some cool days off!

**Comment by Steveplays28** [comment]
Thank you!

**Comment by Steveplays28** [comment]
The fix for this issue has been released in [`v1.8.2`](https://github.com/Steveplays28/realisticsleep/releases/latest).

**Comment by Cape-City** [comment]
CurseForge isn't offering this version for 1.19.x :( In the 1.7.1 version the depends section was like this and this mod can be installed within CF:

  "depends": {
    "fabricloader": ">=0.14.8",
    "minecraft": [
      "1.18.x",
      "1.19.x"
    ],

In the latest Version you changed it to:

  "depends": {
    "fabricloader": ">=0.14.8",
    "minecraft": [
      "<1.20 >=1.18"
    ],

This isn't shown up to install:

![grafik](https://github.com/Steveplays28/realisticsleep/assets/122229367/472c188f-1e8f-4b32-956e-6490aaa72003)

**Comment by Steveplays28** [comment]
Thanks for pointing that out, just fixed it on both CurseForge and Modrinth.
