### ISSUE TITLE
Incompatibility: Realistic Sleep 1.7.1+mc1.18.x-1.19.x and Vanilla Tweaks Datapacks on Fabric 1.19.2

### ISSUE THREAD

**Issue by deideloo** [Steveplays28/realisticsleep#38]
The server hangs on stop command. The following [Vanilla Tweaks](https://vanillatweaks.net/picker/datapacks/) datapacks have this conflict:

- armor statues v2.8.4
- fast leaf decay v2.0.6
- graves v2.8.7
- pillager tools v1.1.3
- track raw statistics v1.5.3
- track statistics v1.1.4  

This isn't a complete list of every possible conflict with Vanilla Tweaks, this is only out of the datapacks tested for my server.

**Comment by Steveplays28** [comment]
Could you try lowering the tick speed multipliers in the config to `1.0`?
This is a similar issue to #37, and I can't seem to recreate it at all.

I play in heavily modded modpacks on all kinds of hardware which makes it even more odd that I can't recreate it.

**Comment by deideloo** [comment]
I tried setting all multipliers to 1.0, server is still hanging on stop. 

`{
  "dawnMessage": "The sun rises.",
  "sendSleepingMessage": true,
  "sendNotEnoughPlayersSleepingMessage": true,
  "sleepSpeedCurve": "LINEAR",
  "sleepSpeedMultiplier": 1.0,
  "blockEntityTickSpeedMultiplier": 1.0,
  "chunkTickSpeedMultiplier": 1.0,
  "raidTickSpeedMultiplier": 1.0,
  "tickDelay": -1
}`

FWIW if the information is useful I haven't tested if this conflict happens on clientside, it's happening on a multiplayer server which otherwise doesn't have any issue.

**Comment by Steveplays28** [comment]
Odd, I've been using Realistic Sleep on a modded server on various hardware (low/mid end for the server) and haven't had this issue.
I've also used it clientside (singleplayer) a lot and haven't ran into issues. I'm really puzzled.

**Comment by deideloo** [comment]
Hmm, let me know if there's any other info you could use on the server config that might give a lead. I did test with WatchDog turned off and it was still hung after several minutes, no clue what's happening at stop that could be making these mods confused by one another...

**Comment by Steveplays28** [comment]
Alright. I'll have to take a deeper look at these Vanilla Tweaks datapacks and how they function to see what might cause the issue.
I'll be on vacation though so that might take a while.

**Comment by crg-mad** [comment]
Nether Portal Coords and Durability Ping from Vanilla Tweaks also causes issues on 1.20. Have not tested 1.19 or 1.18.

**Comment by Steveplays28** [comment]
This issue should also be fixed in release [`v1.8.2`](https://github.com/Steveplays28/realisticsleep/releases/latest).
