### ISSUE TITLE
Time Passing While Sleeping Will Not Pass In Other Dimensions

### ISSUE THREAD

**Issue by LPeter985** [Steveplays28/realisticsleep#39]
To Reproduce, sleep in any other dimensions (other then the overworld, nether, and end)

(I'm talking about modded dimensions)

**Comment by Steveplays28** [comment]
Thanks for the report, I'll take a look!

**Comment by Steveplays28** [comment]
It seems like this is part of a bigger issue involving sleeping in custom dimensions. Apparently this hasn't worked properly for a while and is a vanilla Minecraft bug.

Using a mod such as [Dimension Mutability](https://www.curseforge.com/minecraft/mc-mods/dimension-mutability) might fix this.

**Comment by LPeter985** [comment]
Thanks
