### ISSUE TITLE
Unable to launch the game on minecraft Quilt 1.20.1

### ISSUE THREAD

**Issue by Cinnius** [Steveplays28/realisticsleep#40]
Hi, i love your mode and i play with it from 1.19, but with the update at 1.20.x i have problem:

- With the previous version of Realistic Sleep the game will remain stuck on world generation.
- With the last version of Realistic Sleep (1.8.0) when i click the play button on the launcher the game crash without starting.

I link the crash report of the game.
Thank you for the help :)

[Crash Report.txt](https://github.com/Steveplays28/realisticsleep/files/12206856/Crash.Report.txt)

**Comment by IntM4rco** [comment]
Same on Fabric (Fabric API 0.86.1)

**Comment by Steveplays28** [comment]
This has been fixed in [`v1.8.1`](https://github.com/Steveplays28/realisticsleep/releases/latest)!
