### ISSUE TITLE
Realistic Sleep 1.8.2 bug with Vanilla Tweaks Armor Statues 2.8.5 - Minecraft 1.20.1 with Quilt 0.19.4

### ISSUE THREAD

**Issue by Cinnius** [Steveplays28/realisticsleep#42]
I'm not sure what is causing this bug, but with the new version (1.8.2) the Vanilla Tweaks datapack for Armor Statues don't work correctly.

I noticed this when the command "/trigger as_help" won't launch correctly in some sort of error that won't permit to launch a second time the command.
After some test on other function of the datapack (primary the function inside the book and to generate the book) the trigger from the datapack won't work.

The game still function and no error in displayed, so i don't know what to add at this.

**Comment by Steveplays28** [comment]
Hi Cinnius,
I think that might be related to the removal of the vanilla event scheduling stuff.

I'll see what I can do about it, not sure if it's easily fixable.

**Comment by Steveplays28** [comment]
Looks like I might've fixed it!
![image](https://github.com/Steveplays28/realisticsleep/assets/62797992/2b83fc87-8db2-4f7e-ad31-a1f477b971ab)
![image](https://github.com/Steveplays28/realisticsleep/assets/62797992/14d121e5-8d84-4153-8011-351fdd8f4c9e)

Could you try out the [newest CI/CD build](https://github.com/Steveplays28/realisticsleep/actions)?

**Comment by Cinnius** [comment]
Yes, i tried the newest update and i can confirm that the nether with incendium load correctly and seem to work everything fine (i tried to sleep and put something on the furnace and it worked).

Good job and thanks as always :D

**Comment by Steveplays28** [comment]
Awesome! No problem.
I'll release this, alongside the day counter reset fix as a hotfix later.

**Comment by Steveplays28** [comment]
The fix for this has been released in [`v1.8.3`](https://github.com/Steveplays28/realisticsleep/releases/latest)!
