### ISSUE TITLE
Day count reset!

### ISSUE THREAD

**Issue by FAKHORII** [Steveplays28/realisticsleep#43]
one of the last few version has a bug where it resets the day count and keep it stuck at day 0 at all times

**Comment by Steveplays28** [comment]
Hi Fakhorii,

that'll be fixed in the next release. For now, you can download a fixed version from [GitHub Actions (CI/CD)](https://github.com/Steveplays28/realisticsleep/actions).

**Comment by FAKHORII** [comment]
> Hi Fakhorii,
> 
> that'll be fixed in the next release. For now, you can download a fixed version from [GitHub Actions (CI/CD)](https://github.com/Steveplays28/realisticsleep/actions).

Thank u so much <3 I will wait for the release, I'm sorry I'm so dumb idk how to download stuff from this website XD
another note tho!
with the fix... will it bring the normal day count as it was or its all gone?

**Comment by Steveplays28** [comment]
There's an artifacts section, you have to click on `compiled_jar_files` to download it. That should contain a zip containing the jar.
You want the jar without `sources` in the name.

![image](https://github.com/Steveplays28/realisticsleep/assets/62797992/b63d9f5f-a2cf-456e-a5dd-eef4ed28877b)

The day count won't be restored, you'll have to use `/time set n` for that. Apologies if a world without cheats enabled got broken.

**Comment by FAKHORII** [comment]
I appreciate u Steve, Thank u so much and never Apologies! it happens, I added both Jars, although idk what the other one with sources do! I still add it anyways.. again! thanks for ur time <3

**Comment by Steveplays28** [comment]
No problem! The `sources` jar is the code, you don't need that, it shouldn't do much.
Have fun

**Comment by FAKHORII** [comment]
thank u, have a blessed day <3

**Comment by Steveplays28** [comment]
The fix for this has just been released in [`v1.8.3`](https://github.com/Steveplays28/realisticsleep/releases/latest)!
