### ISSUE TITLE
Incompatible with stellarity

### ISSUE THREAD

**Issue by piebaker** [Steveplays28/realisticsleep#44]
https://modrinth.com/datapack/stellarity
I have no idea why, but realistic sleep changes how the end ender dragon nest/biome/arena is constructed. I can happily open an issue on their end also, but it seems so odd to me that its a sleep mod causing it!

**Comment by Steveplays28** [comment]
There's some issues with certain datapacks, I'm not sure how to solve it yet.
Thanks for the report.

**Comment by piebaker** [comment]
Good to know its not a surprise! Will keep an eye out for any developments

**Comment by Steveplays28** [comment]
Should be fixed, could you try out the newest [CI/CD build](https://github.com/Steveplays28/realisticsleep/actions)?

**Comment by piebaker** [comment]
Yup, back to working!

**Comment by Steveplays28** [comment]
Nice, I'll release it as a hotfix later.

**Comment by Steveplays28** [comment]
Just released the fix in [`v1.8.3`](https://github.com/Steveplays28/realisticsleep/releases/latest)!
