### ISSUE TITLE
Incompatible with More Mobs

### ISSUE THREAD

**Issue by piebaker** [Steveplays28/realisticsleep#45]
[More Mobs](https://modrinth.com/datapack/more-mobs) is an excellent mob-extension mod, but sadly realistic sleep prevents it working :(

**Comment by Steveplays28** [comment]
What version of Realistic Sleep are you using, and is there anything in the logs?

**Comment by piebaker** [comment]
Turns out i had the old version, 1.8.2. Of course updating to 1.8.3 fixes the issue, duh! Thanks again for the excellent update

**Comment by Steveplays28** [comment]
Ahh, all good! Glad the new update fixes your issue as well!
