### ISSUE TITLE
Incompatible with Vanilla tweaks Timber Datapack

### ISSUE THREAD

**Issue by YoshiiS02** [Steveplays28/realisticsleep#47]
As soon as Realistic sleep is added to the mods folder Timber just stops working.
The datapack is clearly still enabled since the command that comes with it still exists but only one block is mined no matter the settings.

Minecraft version 1.20.1
Fabric loader version 0.14.22

**Comment by Steveplays28** [comment]
Hi YoshiiS02, what version of Realistic Sleep are you using?
Could you send a log file as well?

**Comment by YoshiiS02** [comment]
[latest.log](https://github.com/Steveplays28/realisticsleep/files/12643752/latest.log)

mod version is 1.8.3 and it doesn't seem like there's any log output during this behaviour, unless there are other log files that I don't know about

**Comment by Steveplays28** [comment]
Thanks, I'll look into it.

**Comment by Steveplays28** [comment]
I'm getting a bunch of issues when trying to run Timber, even on its own. It's also marked as an experimental datapack on [Vanilla Tweaks' website](https://vanillatweaks.net/picker/datapacks), so I'm going to close this issue as `wontfix`.
For now, I recommend using a serverside mod or a different datapack that accomplishes the same thing.

If the datapack is updated in the future, feel free to open a [new issue](https://github.com/Steveplays28/realisticsleep/issues/new) if there's any compatibility problems.
