### ISSUE TITLE
Mod Incompatibility - Enhanced Celestials

### ISSUE THREAD

**Issue by MLMII** [Steveplays28/realisticsleep#5]
Sleeping in a bed resets the "Lunar Forecast" for Enhanced Celestials so the various "Moons" never happen unless you stay awake every night.

Thank you for your time

**Comment by Steveplays28** [comment]
Hi, I'm aware of a similar issue. This is caused by my mod resetting the day counter after sleeping.
I will look into it soon. Also need to fix a crash on my new mod ([restart-server](https://github.com/steveplays28/restart-server)) while I'm at it.

**Comment by Steveplays28** [comment]
hi, I have been looking into this issue for a few days now, but I can't find the vanilla sleeping code that increases the day counter.
I also don't set the day to 0 on purpose in my code anywhere.

I'm going to ask for some help today on Discord. If you have any clue that'd be appreciated.

Besides, I usually only really work on things during the weekends, so progress is slow.
Luckily I'm on break this week. Thanks for your patience.

**Comment by Steveplays28** [comment]
I seem to have fixed this issue in my development build!
I'll do some more testing to make sure I didn't break any other features.

I'm also going to implement #9 and then push a release soon.

**Comment by Steveplays28** [comment]
Fixed in [1.6.0](https://github.com/Steveplays28/realisticsleep/releases/tag/1.6.0).
