### ISSUE TITLE
time 

### ISSUE THREAD

**Issue by Thefatsparrow** [Steveplays28/realisticsleep#50]
hello! what settings would i change in the config to make days and nights both 15 minutes each and what values would i set them too 

thanks!

**Comment by Steveplays28** [comment]
Hi, please use the Discord server for support. I see you've joined the Discord server already, feel free to ask away in [#general](https://discord.com/channels/746681304111906867/768404604722348032)!

To answer the question, the tick delay doesn't work in reverse yet, it can only make the days night cycle longer.
