### ISSUE TITLE
Lava Farm gets broken

### ISSUE THREAD

**Issue by acendvgnt** [Steveplays28/realisticsleep#54]
Cauldrons are getting filled with water every time I sleep even though the dripstone above them is dripping lava lol
![image](https://github.com/Steveplays28/realisticsleep/assets/85397982/8cd8f559-85af-4964-990b-5264e9c121c1)

**Comment by Steveplays28** [comment]
Hi acendvgnt, I'll look into this bug today!
Weird issue haha

**Comment by acendvgnt** [comment]
I'm on Minecraft 1.20.1 (Fabric) and the mod version is 1.9.1. idk how to send a log file

I skimmed the ServerWorldMixin.java file and its probably caused by the `cauldronBlock.precipitationTick`. Maybe you can add some sort of condition to check whether the cauldron has sky access or smth like that?

**Comment by Steveplays28** [comment]
Fixed in Realistic Sleep [`v1.9.2`](https://github.com/Steveplays28/realisticsleep#download), thanks for the report!
