### ISSUE TITLE
not speeding up time

### ISSUE THREAD

**Issue by BruhKidBruh** [Steveplays28/realisticsleep#58]
i downloaded time control and started messing a around with tick speed in a different world now i cant sleep in my main survival world

**Comment by Steveplays28** [comment]
Hi BruhKidBruh, time control is [not compatible](<https://github.com/Steveplays28/realisticsleep/blob/fc148859ba786e196373a53fe5b7335bbbe62dc3/src/main/resources/fabric.mod.json#L60C1-L63C4>) with Realistic Sleep.
If you want a longer day/night cycle, you can configure this in Realistic Sleep's config, by changing `tickDelay`.

Duplicate of #51.
Thanks for checking out Realistic Sleep.

**Comment by BruhKidBruh** [comment]
no but i uninstalled it

**Comment by BruhKidBruh** [comment]
it works in newer worlds i create but just not that one world
