### ISSUE TITLE
Not speeding up tick rate

### ISSUE THREAD

**Issue by BruhKidBruh** [Steveplays28/realisticsleep#59]
It works in other worlds just not my main survival world.

**Comment by Steveplays28** [comment]
Hi, could you send your log file, after loading into your main survival world?

**Comment by BruhKidBruh** [comment]
Nvm i fixed it. its odd i need to use time control or else i cant sleep. pretty sure it corrupted my save in some way

**Comment by Steveplays28** [comment]
That's weird, really not sure what's going on there.
But if it works, I'll close this issue.
