### ISSUE TITLE
incompatible with fabric seasons

### ISSUE THREAD

**Issue by lostopkk** [Steveplays28/realisticsleep#6]
on my server, every time someone finishes sleeping the day goes back to day 0, this makes the seasons never arrive in fabric seasons, please correct

**Comment by Steveplays28** [comment]
Same issue as #5. I will look into it when I have time.

**Comment by Steveplays28** [comment]
Fixed in [1.6.0](https://github.com/Steveplays28/realisticsleep/releases/tag/1.6.0).
