### ISSUE TITLE
Lower the default speedup multipliers in the config - Mod is causing fabric server to be 9TPS

### ISSUE THREAD

**Issue by VenoPhage** [Steveplays28/realisticsleep#62]
no ideaaa why but spark says this mod is using 50% of the server thread https://spark.lucko.me/yCqmzVCV6P

**Comment by Steveplays28** [comment]
Hi @ExpertNugget, seems like you enabled some parts of the config, such as chunk ticking speedup.
This is very TPS heavy (and noted as such in Mod Menu). I recommend lowering the speedup multipliers and tuning them according to your client/server's performance.

I'll tune down the defaults in the future, since they're currently way too high. This in turn also makes the speedup multipliers not match how long it'd take crops, for example, to grow.
Thanks for reminding me of that issue. I'll leave this issue open until I've fixed that.

**Comment by seefourr** [comment]
sorry, could you explain what you mean? 1.0 is the default value for "chunk tick speed multiplier", which I would have assumed to mean it should tick at 100% of its original speed. Am i misunderstanding this? (i.e. 100% = 100% faster aka 200% speed)

**Comment by Steveplays28** [comment]
@seefourr In the config, almost all tick speed multipliers are set to `25d`, which means it'll tick 25x faster when sleeping.
The exception to this is the chunk tick speed multiplier, which is set to `1d` (1x) by default, meaning there's no speedup and it just runs as normal/like in vanilla, since it causes huge performance issues, and has been replaced with the crop growth, precipitation, and other tick speed multipliers, which are far more efficient.

This default value of `25d` for most of the tick speed multipliers is way too high in comparison to vanilla though. For example, when sleeping, crops grow in 1 day instead of 3 or so like they're supposed to in vanilla, iirc.

**Comment by seefourr** [comment]
so is it the 25x that is/was lagging my server? (my spark profiles look almost identical to the one provided by OP).
Because my chunk tick speed multiplier is also at 1.0x (default) but i'm experiencing very low TPS, ~10, as soon as there is more than 1 or 2 people on my server. 

I've turned all the default 25x config values down to 10x if that will help (although I'm not at home and can't actually test rn) but I especially don't see why it should be lagging the server at all when nothing even related to sleeping is happening

**Comment by Steveplays28** [comment]
@seefourr If you take a look at the code, a lot happens in [`tickChunkInject`](<https://github.com/Steveplays28/realisticsleep/blob/fc148859ba786e196373a53fe5b7335bbbe62dc3/src/main/java/com/github/steveplays28/realisticsleep/mixin/ServerWorldMixin.java#L287>), such as the crop growth/precipitation tick speed multipliers. Try lowering all of them down to suit your machine's performance and the speed you'd like the mechanics to work at while sleeping.

**Comment by seefourr** [comment]
i'm not a coding person so it wouldn't make sense to me, but I get what you're saying about lowering the multipliers.

What I'm saying is it doesn't make any sense that my server's performance is absolutely tanked by just having this mod even though it's daytime in-game and it theoretically shouldn't be doing anything.

**Comment by Steveplays28** [comment]
Yeah that's odd. The tick speed multipliers disable themselves when there isn't anyone sleeping.
I'll double check to see if that actually works as intended.

**Comment by seefourr** [comment]
That would actually make sense, I forgot about this but I noticed yesterday that my potatoes were growing a _lot_ faster than they should during the day.

**Comment by Steveplays28** [comment]
There's an option in the settings that allows sleeping during daytime. Could you check if that's enabled, and if anyone is sleeping on your server?
I tried reproducing the issue, but it works fine for me on 1.20.3 Fabric, in singleplayer.
What MC version and Realistic Sleep version do you have @seefourr?

**Comment by seefourr** [comment]
I am on 1.20.1 fabric and my realistic sleep is 1.10.2. The config option for daytime sleeping has always been disabled for me.

**Comment by Steveplays28** [comment]
@seefourr Alright. That's super weird then.
Could you check if anyone was sleeping while this was happening? I think that's the last possibility.

**Comment by VenoPhage** [comment]
I've given up with dealing with Minecrafts awful performance and my server is no longer running, but what I can add to this now is that even after removing this mod I was still having bad TPS, only noteworthy things of my server is it only had server side mods. I can also provide my mod list if that's at all helpful

**Comment by Steveplays28** [comment]
@ExpertNugget Alright. I can take a look at that if it's not a hassle to send the list over.
Thank you both for your patience with this.

**Comment by VenoPhage** [comment]
Here it is, hope this helps
- [KleeSlabs](https://mods.twelveiterations.com/mc/kleeslabs) [16.0.1]
- [PolyFactory](https://pb4.eu) [0.3.4+1.20.4]
- [YUNG's Better End Island](https://www.curseforge.com/minecraft/mc-mods/yungs-better-end-island-fabric) [1.20.4-Fabric-2.4.1]
- [Styled Chat](https://pb4.eu) [2.4.0+1.20.3]
- ChoiceTheorem's Overhauled Village [3.4.2]
- [Fabric Language Kotlin](https://minecraft.curseforge.com/projects/fabric-language-kotlin) [1.10.19+kotlin.1.9.23]
- [Just Enough Items](https://www.curseforge.com/minecraft/mc-mods/jei) [17.3.0.49]
- BetterThanMending [2.0.0]
- Improved Signs [1.3.3]
- [YUNG's Better Nether Fortresses](https://www.curseforge.com/minecraft/mc-mods/yungs-better-nether-fortresses-fabric) [1.20.4-Fabric-2.4.2]
- [Collective](https://serilum.com/mod/collective) [7.40]
- [ViaRewind](https://viaversion.com/rewind) [3.0.7-SNAPSHOT]
- [Cloth Config v13](https://minecraft.curseforge.com/projects/cloth-config) [13.0.121]
- [Terralith](https://www.stardustlabs.net/) [2.4.11]
- [Enchant Tweaker](https://modrinth.com/mod/enchant-tweaker) [1.4.9+mc1.20.3-1.20.4]
- [Concurrent Chunk Management Engine](https://modrinth.com/mod/c2me-fabric) [0.2.0+alpha.11.58]
- [Ledger](https://quiltservertools.github.io/Ledger/latest/) [1.2.10]
- [Lithostitched](https://modrinth.com/mod/lithostitched/) [1.1.5]
- [Polydex](https://pb4.eu) [1.0.1+1.20.4]
- [Balm](https://mods.twelveiterations.com/) [9.0.6]
- ServerCore [1.4.0+1.20.3]
- [YUNG's Better Ocean Monuments](https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments-fabric) [1.20.4-Fabric-3.4.1]
- [YUNG's Better Jungle Temples](https://www.curseforge.com/minecraft/mc-mods/yungs-better-jungle-temples-fabric) [1.20.4-Fabric-2.4.1]
- [Starlight](https://www.curseforge.com/minecraft/mc-mods/starlight) [1.1.3+fabric.f5dcd1a]
- [YUNG's Better Witch Huts](https://www.curseforge.com/minecraft/mc-mods/yungs-better-witch-huts-fabric) [1.20.4-Fabric-3.4.1]
- [Architectury](https://architectury.github.io/architectury-documentations/) [11.1.17]
- [True Ending: Ender Dragon Overhaul](https://modrinth.com/datapack/true-ending) [1-v1.1.0c]
- [ViaFabric](https://viaversion.com/fabric) [0.4.13+64-main]
- serializationisbad-1.3
- [YUNG's API](https://www.curseforge.com/minecraft/mc-mods/yungs-api-fabric) [1.20.4-Fabric-4.4.2]
- [PolyDecorations](https://pb4.eu) [0.2.2+1.20.4]
- [Universal Graves](https://pb4.eu) [3.2.1+1.20.3]
- [YUNG's Better Desert Temples](https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples-fabric) [1.20.4-Fabric-3.4.1]
- [Polymer](https://pb4.eu) [0.7.6+1.20.4]
- [Sensible Sleepiness](https://github.com/ArkoSammy12) [0.0.1-1.20+]
- Geyser-Fabric [2.2.2-SNAPSHOT]
- [Incendium](https://www.stardustlabs.net/) [5.3.4]
- [Trinkets](https://www.curseforge.com/minecraft/mc-mods/trinkets-fabric) [3.8.0+polymerport.2]
- Simple Discord Link [3.0.1]
- [spark](https://spark.lucko.me/) [1.10.58]
- [Bottle Your Xp](https://serilum.com/mod/bottle-your-xp) [3.3]
- [More Tools (Polymer)](https://mc.smto.pw/) [1.0.0]
- [FastBack](https://pcal43.github.io/fastback/) [0.17.0+1.20.4-fabric]
- View Distance Fix [1.20.4-1.0.2]
- [YUNG's Better Strongholds](https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds-fabric) [1.20.4-Fabric-4.4.1]
- [BlueMap](https://github.com/BlueMap-Minecraft) [3.20]
- [Bigger Better End Cities](https://fabricmc.net/) [1.20.4-1.0.4]
- [CraterLib](https://modrinth.com/mod/craterlib) [1.1.0]
- Monsters in the Closet [1.0.3+1.20]
- Floodgate-Fabric [2.2.0-SNAPSHOT]
- [YUNG's Better Dungeons](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons-fabric) [1.20.4-Fabric-4.4.1]
- [ViaVersion](https://viaversion.com/) [4.9.4-SNAPSHOT]
- [Simple Voice Chat](https://modrepo.de/minecraft/voicechat/overview) [1.20.4-2.5.9]
- Very Many Players [0.2.0+beta.7.138]
- [Get Off My Lawn ReServed](https://pb4.eu) [`1.11.0`+1.20.3-rc1]
- [Styled Player List](https://pb4.eu) [3.3.0+1.20.3]
- [Tree Harvester](https://serilum.com/mod/tree-harvester) [8.7]
- [Right Click Harvest](https://github.com/JamCoreModding/right-click-harvest) [4.1.4+1.20.4]
- [Fabric API](https://fabricmc.net) [0.96.11+1.20.4]
- Voice Chat Interaction [1.20.4-1.0.6]
- [ViaBackwards](https://viaversion.com/backwards) [4.9.3-SNAPSHOT]
- [JamLib](https://github.com/JamCoreModding/jamlib) [1.0.6+1.20.4]
- [YUNG's Extras](https://www.curseforge.com/minecraft/mc-mods/yungs-extras-fabric) [1.20.4-Fabric-4.4.0]
- [YUNG's Better Mineshafts](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-fabric) [1.20.4-Fabric-4.4.1]
- [Lithium](https://jellysquid.me/projects/) [0.12.1]
- [Illager Expansion Recrafted](https://pb4.eu) [1.1.0]
- Polysit [0.5.3+mc.1.20.1]

**Comment by seefourr** [comment]
Nope, definitely nobody sleeping. The only possible thing I can think of was I closed the server while my character was in a bed one time, but the TPS had been on the high side already way before that. TPS was justabout fine although the MSPT was a little higher than I'd like (but still below 50) with 1 or 2 people, but when some more people (up to 6 at most) joined it really started struggling. 

The server thread on my spark profile looked like the original one from OP but with a _much_ higher percentage being the shown part. (screenshot is from OPs spark profile because my logs seem to be bugged and I can't find any of my own spark profiles).

<img width="1884" alt="Screenshot 2024-03-25 at 10 00 51 am" src="https://github.com/Steveplays28/realisticsleep/assets/106939690/fdc3b959-e048-4756-bb5c-506fd0cc41eb">

**Comment by seefourr** [comment]
I do have quite a few mods on the server though so it could be a conflict of sorts; here's a mod list straight from my most recent log:
	- advancednetherite 2.0.3-1.20.1
	- alloy_forgery 2.1.2+1.20
	- amplified_nether 1.2.4
	- architectury 9.2.14
	- asynclocator 1.3.0
	- balancedrecall 1.0.5
	- bankstorage 1.0.1
	- bclib 3.0.14
	   \-- wunderlib 1.1.5
	- better_beacons 2.0.0
	   |-- mixinextras 0.3.5
	   \-- reach-entity-attributes 2.4.0
	- betterarcheology 1.1.6-1.20.1
	- betterdeserttemples 1.20-Fabric-3.0.3
	   \-- org_reflections_reflections 0.10.2
	- betterdungeons 1.20-Fabric-4.0.3
	- betterend 4.0.11
	- betterendisland 1.20-Fabric-2.0.6
	- betterfortresses 1.20-Fabric-2.0.6
	- betterjungletemples 1.20-Fabric-2.0.4
	- bettermineshafts 1.20-Fabric-4.0.4
	- betteroceanmonuments 1.20-Fabric-3.0.4
	- betterstrongholds 1.20-Fabric-4.0.3
	- betterthanmending 1.3.0
	- betterwitchhuts 1.20-Fabric-3.0.3
	- bigendcitiesmod 1.20.1-1.0.4
	- blockrunner 8.0.4
	- boids 1.1.1
	- bookshelf 20.1.9
	- bosses_of_mass_destruction 1.7.5-1.20.1
	   |-- maelstrom_library 1.6.1-1.20
	   \-- multipart_entities 1.5-1.20
	- c2me 0.2.0+alpha.11.5
	   |-- c2me-base 0.2.0+alpha.11.5
	   |-- c2me-client-uncapvd 0.2.0+alpha.11.5
	   |-- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.11.5
	   |-- c2me-fixes-general-threading-issues 0.2.0+alpha.11.5
	   |-- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.11.5
	   |-- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.11.5
	   |-- c2me-notickvd 0.2.0+alpha.11.5
	   |-- c2me-opts-allocs 0.2.0+alpha.11.5
	   |-- c2me-opts-chunk-access 0.2.0+alpha.11.5
	   |-- c2me-opts-chunkio 0.2.0+alpha.11.5
	   |-- c2me-opts-math 0.2.0+alpha.11.5
	   |-- c2me-opts-scheduling 0.2.0+alpha.11.5
	   |-- c2me-opts-worldgen-general 0.2.0+alpha.11.5
	   |-- c2me-opts-worldgen-vanilla 0.2.0+alpha.11.5
	   |-- c2me-rewrites-chunk-serializer 0.2.0+alpha.11.5
	   |-- c2me-rewrites-chunkio 0.2.0+alpha.11.5
	   |-- c2me-server-utils 0.2.0+alpha.11.5
	   |-- c2me-threading-chunkio 0.2.0+alpha.11.5
	   |-- c2me-threading-lighting 0.2.0+alpha.11.5
	   |-- c2me-threading-worldgen 0.2.0+alpha.11.5
	   |-- com_ibm_async_asyncutil 0.1.0
	   |-- net_objecthunter_exp4j 0.4.8
	   \-- org_threadly_threadly 7.0
	- cardinal-components 5.2.2
	   |-- cardinal-components-base 5.2.2
	   |-- cardinal-components-block 5.2.2
	   |-- cardinal-components-chunk 5.2.2
	   |-- cardinal-components-entity 5.2.2
	   |-- cardinal-components-item 5.2.2
	   |-- cardinal-components-level 5.2.2
	   |-- cardinal-components-scoreboard 5.2.2
	   \-- cardinal-components-world 5.2.2
	- cave_dweller 1.3.0
	- cerbons_api 1.1.0
	- chefsdelight 1.0.3-fabric-1.20.1
	- chunky 1.3.138
	- chunkyextended 2.1.1
	- cloth-config 11.1.118
	   \-- cloth-basic-math 0.6.1
	- collective 7.40
	- completeconfig 2.5.3
	   |-- completeconfig-base 2.5.3
	   |-- completeconfig-gui-cloth 2.5.3
	   \-- completeconfig-gui-yacl 2.5.3
	- creeperoverhaul 3.0.2
	   \-- resourcefullib 2.1.20
	        |-- com_teamresourceful_bytecodecs 1.0.2
	        \-- com_teamresourceful_yabn 1.0.3
	- cristellib 1.1.5
	   \-- blue_endless_jankson 1.2.3
	- ctov 3.4.2
	- cupboard 1.20.1-2.6
	- darkutils 17.0.3
	- deathbackup 3.3
	- deathknell 10.0.4
	- debugify 1.20.1+2.0
	- dimensional-tracker 1.3.0
	- disableportalchecks 1.0.0
	- dismountentity 3.2
	- dungeons_arise 2.1.57
	- echochest 8.0.0
	- elytraslot 6.3.0+1.20.1
	- ember_kiln 1.0.4
	- endermanoverhaul 1.0.4
	- endrem 5.2.4
	- fabric-api 0.92.0+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.1+1802ada577
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.4+1802ada577
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabric-language-kotlin 1.10.19+kotlin.1.9.23
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.23
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabrication 3.4.10+1.20
	   \-- lib39-deferral 1.5.0-pre2.2+1.19.3
	- fabricloader 0.15.7
	   \-- mixinextras 0.3.5
	- farmersdelight 1.20.1-1.4.3
	- fastpaintings 1.20-1.2.5
	- ferritecore 6.0.1
	- forgeconfigapiport 8.0.0
	- geckolib 4.4.4
	   \-- com_eliotlash_mclib_mclib 20
	- giantspawn 5.0
	- globalxp 1.10.4
	- grabbymobs 1.5
	- illagerinvasion 8.0.4
	   \-- extensibleenums 7.0.1
	- infinitetrading 4.3
	- inventorytotem 3.2
	- jade 11.8.0
	- jadeaddons 5.2.3
	- java 19
	- keepmysoiltilled 2.2
	- krypton 0.2.3
	   \-- com_velocitypowered_velocity-native 3.2.0-SNAPSHOT
	- lazydfu 0.1.3
	- legacies_and_legends 1.3.7
	- life-crystals 1.0.3
	- lithium 0.11.2
	- lithostitched 1.1.5
	- lootr 0.7.30.77
	- majruszlibrary 7.0.5
	- majruszsaccessories 1.5.2
	- majruszsenchantments 1.10.7
	- memoryleakfix 1.1.5
	- midnightlib 1.4.1
	- minecraft 1.20.1
	- miners-compass 1.0.0+1.20.1
	- modernfix 5.14.0+mc1.20.1
	- moonlight 1.20-2.11.4
	- moremobvariants 1.2.2
	- mr_2032_worldheight 1.17+
	- mr_ctov_chefsdelightcompat 2.0
	- mr_ctov_farmersdelightcompat 2.1
	- mr_refined_advancements 1.0.3d
	- mr_remove_terralithintromessage 1.0
	- mythicmetals 0.19.6+1.20.1
	   |-- additionalentityattributes 1.4.0+1.20.0
	   |-- common-protection-api 1.0.0
	   \-- reach-entity-attributes 2.4.0
	- near_world_spawn 1.0
	- njb 1.1.0
	- noanimaltemptdelay 1.1
	- nochatreports 1.20.1-v2.2.2
	   |-- fabric-rendering-v1 3.0.6+b3afc78b82
	   \-- fabric-screen-api-v1 2.0.6+b3afc78b82
	- owo 0.11.2+1.20
	- passiveshield 3.4
	- pehkui 3.7.12+1.14.4-1.20.4
	   \-- kanos_config 0.4.1+1.14.4-1.19.4
	- permanentsponges 8.1.1
	- plentyplates 8.0.0
	- puzzleslib 8.1.17
	   \-- puzzlesaccessapi 8.0.7
	- pvpflag 1.3.0+1.20.1
	- realisticbees 3.8
	- realisticsleep 1.10.2+mc1.20-1.20.1
	   \-- server_translations_api 2.0.0+1.20
	        \-- packet_tweaker 0.4.0+1.19.4
	- resourcefulconfig 2.1.2
	- ringsofascension 2.0.2
	- roughlyenoughitems 12.0.684
	   \-- error_notifier 1.0.9
	- scaffoldingdropsnearby 3.2
	- sculkhornid 1.4.1
	- seasons 2.2.1+1.20
	- seasonsdelightcompat 1.0-1.3.9
	- servercore 1.3.9+1.20.1
	   |-- com_electronwill_night-config_core 3.6.6
	   |-- com_electronwill_night-config_toml 3.6.6
	   |-- fabric-permissions-api-v0 0.2-SNAPSHOT
	   \-- placeholder-api 2.1.2+1.20.1
	- serverpause 1.1.0
	- sessility 0.3
	- shulkerdropstwo 3.3
	- simplemod 1.20.1
	- simpleveinminer 1.4.2
	   |-- cloth-basic-math 0.6.1
	   \-- completeconfig-gui-cloth 2.4.0
	- smoothchunk 1.20.1-3.6
	- spark 1.10.53
	- spawnproof-villagers 1.0.0+1.19.4
	- supplementaries 1.20-2.8.4
	   \-- mixinsquared 0.1.1
	- t_and_t 1.12
	- tectonic 2.2.1
	- terralith 2.4.11
	- thoroughfabric 1.0
	- timestacker 1.1.3
	- trade_cycling 1.20.1-1.0.10
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da82
	   \-- fabric-screen-api-v1 2.0.6+b3afc78b82
	- treasuredistance 1.20.1-1.0.1
	- trinkets 3.7.2
	- underground_bunkers 1.0.3
	- villagersffh 0.5.1
	- wardentools 2.4.0+mc1.20.1
	- warriorrage 1.20.1-fabric-1.0.0
	- wooltweaks 3.3
	- yungsapi 1.20-Fabric-4.0.4
	   \-- org_javassist_javassist 3.29.2-GA
	- yungsbridges 1.20-Fabric-4.0.3
	- yungsextras 1.20-Fabric-4.0.3

But I noticed a big performance jump when this mod was removed.

**Comment by Steveplays28** [comment]
Modlists look fairly standard to me.
I'll try again later to reproduce this issue. In my testing I didn't encounter this though. I looked at a profiler and didn't see any running methods of mine while nobody was sleeping. I'll check with a debugger as well later.

**Comment by Steveplays28** [comment]
I've changed the default tick speed multiplier for interactions to `5` in [`v1.11.0`](https://github.com/steves-underwater-paradise/stevesrealisticsleep/releases/latest).
