### ISSUE TITLE
Update to 1.20.5-1.21

### ISSUE THREAD

**Issue by 500-internal-server-error** [Steveplays28/realisticsleep#64]
Would love to use this mod on the newer versions of MC. Not sure how broken it is but if I force the loader to load the mod anyway I see mixins failing to apply.

**Comment by Steveplays28** [comment]
Hi, I'll update Realistic Sleep when I have time.

**Comment by Ryuo1** [comment]
Please update it to 1.21 too.

i come here everyday to check if it has received an update.

**Comment by Legendmanj** [comment]
bump, notify me if the version has been updated! ggs

**Comment by Steveplays28** [comment]
I likely won't be releasing a new version of Realistic Sleep for Minecraft 1.20.2-1.20.6, but I've ported the mod to multiloader and will be releasing a 1.21-1.21.1 version!

**Comment by Steveplays28** [comment]
I've dropped support for Minecraft 1.20.2-1.20.6, but Minecraft 1.21-1.21.1 support has been released in [`v1.11.0`](https://github.com/steves-underwater-paradise/stevesrealisticsleep/releases/latest).
