### ISSUE TITLE
[Feature Request] Option to disable overlay/vignette while sleeping

### ISSUE THREAD

**Issue by EnragedPotato** [Steveplays28/realisticsleep#68]
Not sure how feasible this is in reality but would it be possible to allow for removing, or reducing, Minecraft's dark blue-ish overlay that fades in when you go to bed in-game? I think it would really let this mod's pretty time-lapses shine instead of being hidden behind a filter all the time.

That said, if this feature isn't within the scope of the mod or just isn't really possible without unnecessary effort then feel free to close this.

Thanks for your time, love the mod.

**Comment by Steveplays28** [comment]
Hi EnragedPotato, thanks for the suggestion and kind words!

I can look into this, seems like a cool feature to have!
I'll most likely look into this after porting all versions of Realistic Sleep to (Neo)Forge.

**Comment by Steveplays28** [comment]
Released in [`v1.11.0`](https://github.com/steves-underwater-paradise/stevesrealisticsleep/releases/latest).

**Comment by EnragedPotato** [comment]
Amazing! Thank you so much for taking the time to add this, I love it. This is absolutely the GOAT Minecraft sleeping mod for me now, lol, the timelapses are so pretty.

**Comment by Steveplays28** [comment]
Glad to hear you like Realistic Sleep @EnragedPotato, have fun playing!
