### ISSUE TITLE
Crash on startup (Minecraft 1.21-1.21.1)

### ISSUE THREAD

**Issue by BetterMetal** [Steveplays28/realisticsleep#70]
Game crashes when I open the game

The game crashed whilst initializing game
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

I am playing on version 1.21.1 neoforge-21.1.37
stevesrealisticsleep-neoforge-1.11.0+mc1.21-1.21.1

The only other mod is the dependency cloth-config-15.0.130-neoforge and it works on its own

I hope this can be fixed soon because this is the exact mod I was looking for

**Comment by Weigurde** [comment]
can you attach your log?

**Comment by Steveplays28** [comment]
I've fixed this in the 1.21-1.21.1 branch, but I wasn't able to release a new version yesterday because of the CurseForge outage. Thanks for the report either way!

**Comment by Steveplays28** [comment]
Fixed in [`v1.11.1`](https://github.com/steves-underwater-paradise/stevesrealisticsleep/releases/latest).
