### ISSUE TITLE
[Fabric 1.21.1] Client crashing on loading.

### ISSUE THREAD

**Issue by NovaLynxie** [Steveplays28/realisticsleep#74]
Hi there! I am trying to load your mod in my fabric pack, but it keeps repeatedly crashing. I am unsure if it's identical to issue #70, but I am experiencing a client crash when attempting to load this mod. It could not get further than an instant crash before loading the game window itself.
I have tried loading with just the mod alone and rolling it back to a previous version; however, it refuses to even get into the game loading screen, making the game unplayable with this mod installed. 

Please can this be looked into? I have attached the crash log and latest logs below for debugging.
Latest Log: [latest.log](https://github.com/user-attachments/files/17203854/latest.log)
Crash Report: [crash-2024-10-01_11.51.12-client.txt](https://github.com/user-attachments/files/17203852/crash-2024-10-01_11.51.12-client.txt)

Running Fabric 0.16.5 for 1.21.1
Mod version: 1.11.1+mc1.21-1.21.1

**Comment by Steveplays28** [comment]
Hi NovaLynxie, you're missing [Architectury API](https://modrinth.com/mod/architectury-api).
Let me know if you still run into any issues after installing Architectury API!

**Comment by NovaLynxie** [comment]
That fixed my issue, the game loaded correctly this time. However, neither my launcher (Prism Launcher) nor the mod's page mentioned of such a dependency. Thank you for the quick reply.

**Comment by Steveplays28** [comment]
Glad that fixed the issue, I'll add the dependency to the mod page and check if it's correctly defined in the `fabric.mod.json`, `neoforge.mods.toml` and `mods.toml` files.
