### ISSUE TITLE
Minimum amount of players to start skipping the night

### ISSUE THREAD

**Issue by CapoFantasma97** [Steveplays28/realisticsleep#8]
A config option to set how many players in percentage need to sleep to start skipping the night.

One player deciding to accellerate the night for the other 5 isn't very democratic; even the opposite is true: people can avoid sleeping and designate a single player to skip the night.

**Comment by Steveplays28** [comment]
Great suggestion, thanks. I'll also add this one to the next release. Should be fairly straightforward to implement

**Comment by Steveplays28** [comment]
I've implemented this in [`development@485095db8d4ae37333e9d85c1b1bfdf4e3df6f37`](https://github.com/Steveplays28/realisticsleep/commit/485095db8d4ae37333e9d85c1b1bfdf4e3df6f37)
It simply uses the PLAYERS_SLEEPING_PERCENTAGE gamerule that is in vanilla Minecraft to determine how many people are required to sleep through the night.

I've also simplified the actionbar sleeping message in [`development@9597bb99ee2ecd212659352dc07c79b939f781cb`](https://github.com/Steveplays28/realisticsleep/commit/9597bb99ee2ecd212659352dc07c79b939f781cb)

I'll need to test these changes, and then I'll start working on adding your other feature request!  
If you're able to test I'd appreciate that, though no worries if you can't, I'll have to find some other people then.

**Comment by CapoFantasma97** [comment]
I don't have the means to try it yet with multiple people, but if you want to organize a test run I'll try to be there and hopefully bring a friend.

**Comment by Steveplays28** [comment]
Cool, thanks! Are you in the [PrismLauncher Discord server](https://discord.gg/prismlauncher)?

**Comment by Steveplays28** [comment]
Added in [1.6.0](https://github.com/Steveplays28/realisticsleep/releases/tag/1.6.0).
