### ISSUE TITLE
Cats not giving "gifts" when they sleep with player on bed.

### ISSUE THREAD

**Issue by LGCreativity** [Steveplays28/realisticsleep#81]
There's a feature in vanilla Minecraft with tamed cats where if set to follow (or wander with some mods) they will cuddle with you when you sleep. When you get up, there's a chance for the cat to leave you a "gift" it acquired while hunting in the night. This is usually common junk items like rotten flesh or string, but sometimes they can find phantom membranes rabbit feet or rabbit hide.

I've found that since I installed the mod, my tamed cat hasn't dropped anything the past dozen or so times I've slept.

**Comment by Steveplays28** [comment]
Thanks for the report LGCreativity, I'm looking into it!

**Comment by Steveplays28** [comment]
This was a fun little bug to work on, didn't know cats occasionally gave gifts! Thanks again.
The fix has been released in [`v1.11.2`](https://github.com/steves-underwater-paradise/stevesrealisticsleep/releases/latest).

**Comment by LGCreativity** [comment]
Awesome! In vanilla, the feature isn't _too_ useful aside from the cat giving the occasional phantom membrane (I love slow falling potions). But I almost rely on it in my modpack since it's one of the easiest ways to get rabbit hide to craft a backpack. (Biomes O' Plenty makes it REALLY hard to find rabbits). Thanks for the quick fix!

**Comment by Steveplays28** [comment]
No problem!
