### ISSUE TITLE
Setting speed to scale exponentially instead of linearly

### ISSUE THREAD

**Issue by CapoFantasma97** [Steveplays28/realisticsleep#9]
A setting to scale speeding up of time to work exponentially based on the amount of players sleeping.

Encourages people to sleep as it's far more efficient when multiple players sleep.

**Comment by Steveplays28** [comment]
Good suggestions! I'll implement this for next release.

**Comment by Steveplays28** [comment]
I need to switch to a decent config library, lmao

Gonna postpone this to release 1.7.0.

**Comment by Steveplays28** [comment]
Ran into some issues with the time predictions on this one. Not going to implement this for now, I fear I'll get burnt out.

**Comment by Steveplays28** [comment]
I've just implemented an exponential curve for the sleep speed, the time prediction isn't always accurate, though that's an issue for later.

**Comment by Steveplays28** [comment]
This feature has been released in [`v1.9.0`](https://github.com/Steveplays28/realisticsleep/releases/latest)!
